[project]
name = "chess-blockchain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "eth-utils>=5.3.1",
    "moccasin>=0.4.3",
    "vyper>=0.4.3",
]
